package by.peekhovsky.newsportal.models.users;

import by.peekhovsky.newsportal.models.news.News;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "user", schema = "public")
public class User {
    /**
     * User id in database.
     * It is autogenerated value.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Login name.
     */
    private String login;
    /**
     * Codified password.
     */
    private String hashPassword;
    /**
     * A first name.
     */
    private String firstName;
    /**
     * Last name.
     */
    private String lastName;
    /**
     * User state.
     */
    @Enumerated(value = EnumType.STRING)
    private UserState userState;

    @ManyToOne
    private List<News> news;
}