package by.peekhovsky.newsportal.model.users;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "user", schema = "public")
public class User {
    /**
     * User id in database.
     * It is autogenerated value.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Login name.
     */
    private String login;
    /**
     * Codified password.
     */
    private String hashPassword;
    /**
     * A first name.
     */
    private String firstName;
    /**
     * Last name.
     */
    private String lastName;
    /**
     * User state.
     */
    @Enumerated(value = EnumType.STRING)
    private UserState userState;
}